version: "3"

services:
  redis:
    image: redis:alpine

    restart: on-failure
  
    networks:
      - "re-ex"
  
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  express:
    build:
      context: ./express-app


    restart: on-failure

    environment:
      -  NODE_ENV=production

    depends_on:
      - redis
    
    networks:
      - "re-ex"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    ports:
      - "80:80"
    

networks:
  re-ex:
    driver: bridge